# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='proto/UnitTable.proto',
  package='Sheet',
  serialized_pb='\n\x15proto/UnitTable.proto\x12\x05Sheet\";\n\tUnitTable\x12\r\n\x02id\x18\x01 \x02(\x05:\x01\x30\x12\x10\n\x06prefab\x18\x02 \x01(\t:\x00\x12\r\n\x05\x61rray\x18\x03 \x03(\x05\"2\n\x0fUnitTable_ARRAY\x12\x1f\n\x05items\x18\x01 \x03(\x0b\x32\x10.Sheet.UnitTable')




_UNITTABLE = descriptor.Descriptor(
  name='UnitTable',
  full_name='Sheet.UnitTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Sheet.UnitTable.id', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='prefab', full_name='Sheet.UnitTable.prefab', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='array', full_name='Sheet.UnitTable.array', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=91,
)


_UNITTABLE_ARRAY = descriptor.Descriptor(
  name='UnitTable_ARRAY',
  full_name='Sheet.UnitTable_ARRAY',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='items', full_name='Sheet.UnitTable_ARRAY.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=93,
  serialized_end=143,
)

_UNITTABLE_ARRAY.fields_by_name['items'].message_type = _UNITTABLE
DESCRIPTOR.message_types_by_name['UnitTable'] = _UNITTABLE
DESCRIPTOR.message_types_by_name['UnitTable_ARRAY'] = _UNITTABLE_ARRAY

class UnitTable(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNITTABLE
  
  # @@protoc_insertion_point(class_scope:Sheet.UnitTable)

class UnitTable_ARRAY(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _UNITTABLE_ARRAY
  
  # @@protoc_insertion_point(class_scope:Sheet.UnitTable_ARRAY)

# @@protoc_insertion_point(module_scope)
