//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: proto/StateTable.proto
namespace Sheet
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StateTable")]
  public partial class StateTable : global::ProtoBuf.IExtensible
  {
    public StateTable() {}
    
    private int _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _desc = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"desc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string desc
    {
      get { return _desc; }
      set { _desc = value; }
    }
    private int _movePriority = (int)0;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"movePriority", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int movePriority
    {
      get { return _movePriority; }
      set { _movePriority = value; }
    }
    private int _moveMode = (int)0;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"moveMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((int)0)]
    public int moveMode
    {
      get { return _moveMode; }
      set { _moveMode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"StateTable_ARRAY")]
  public partial class StateTable_ARRAY : global::ProtoBuf.IExtensible
  {
    public StateTable_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<Sheet.StateTable> _items = new global::System.Collections.Generic.List<Sheet.StateTable>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Sheet.StateTable> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}